services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "6868:8080"
    networks:
      - my-network-name
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bd_EcoVolt
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - API_TOKEN=sk_14050.w5IiZP8rPe5uRDITZ6LnIPyDDBnO9hK5
      - SECURITY_JWT_SECRET=ElLadoMisteriosoDeLaIslaWuuWuuXD
      - SECURITY_JWT_EXPIRATION_MS=86400000

  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    container_name: db
    networks:
      - my-network-name
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bd_EcoVolt
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bd_EcoVolt"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  my-network-name:
    name: springcloud
