spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_EcoVolt
spring.datasource.username=postgres
spring.datasource.password=pamt161616
spring.datasource.driver-class-name=org.postgresql.Driver

#TOKEN RENIEC
api.token=sk_14050.w5IiZP8rPe5uRDITZ6LnIPyDDBnO9hK5

# JWT
security.jwt.secret=ecovolt-demo-secret-key-change-me-please-32-chars
security.jwt.expiration-ms=86400000

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
