spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_EcoVolt
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#TOKEN RENIEC
api.token=sk_14050.w5IiZP8rPe5uRDITZ6LnIPyDDBnO9hK5

# JWT
security.jwt.secret=ElLadoMisteriosoDeLaIslaWuuWuuXD
security.jwt.expiration-ms=86400000

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail (verificacion de cuenta)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:ecovoltp@gmail.com}
spring.mail.password=${MAIL_PASSWORD:heiq jwqt zkbo zknc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_USERNAME:ecovoltp@gmail.com}
